modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]] #mandatory
modId="sporeblossomspollinate"
version="${file.jarVersion}" 
displayName="Spore Blossoms Pollinate"
logoFile="icon.png" 
credits="Ragnaraven"
issueTrackerURL="https://github.com/Ragnaraven/SporeBlossomsPollinate/issues"
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/spore-blossoms-pollinate/files"
authors="Ragnaraven" 
description='''
Makes spore blossoms pollinate in a configurable radius!
.'''

[[dependencies.sporeblossomspollinate]]
	    modId="forge"
	    mandatory=true
	    versionRange="[40,)"
	    ordering="NONE"
	    side="BOTH"

[[dependencies.sporeblossomspollinate]]
	    modId="minecraft"
	    mandatory=true
versionRange="[1.18.2, 1.19)"
	    ordering="NONE"
	    side="BOTH"